acc/urls.py
from turtle import update
from django.urls import path
from acc import views

app_name = "acc"

urlpatterns =[
    path('index/', views.index, name='index'),
    path('login/', views.userlogin, name='login'),
    path('logout/', views.userlogout, name='logout'),
    path('signup/', views.signup,name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('profile/', views.profile, name='profile'),
    path('chpass/', views.chpass, name='chpass')
]

board/urls.py
from django.urls import path
from . import views

app_name = "board"

urlpatterns = [
    path('index/' , views.index, name="index"),
    path('detail/<bpk>', views.detail, name="detail"),
    path('delete/<bpk>', views.delete, name='delete'),
    path('create/', views.create, name='create'),
    path('update/<bpk>', views.update, name='update'),
    path('creply/<bpk>', views.creply, name='creply'),
    path('dreply/<bpk>/<rpk>', views.dreply, name='dreply')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include('acc.urls')),
    path('board/', include('board.urls')),
    path('trans/', include('trans.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trans/urls.py
from django.urls import path
from . import views

app_name = "trans"

urlpatterns = [
    path('index/' , views.index, name="index")
]

acc/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pic = models.ImageField(upload_to="user/%y/%m")
    comment = models.TextField()
    point = models.IntegerField(default=0)

    def getpic(self):
        if self.pic:
            return self.pic.url
        return "/media/noimage.png"

board/models.py
from django.db import models
from acc.models import User

# Create your models here.
class Board(models.Model):
    subject = models.CharField(max_length=100)
    writer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="writer")
    content = models.TextField()
    pubdate = models.DateTimeField()
    likey = models.ManyToManyField(User, blank=True, related_name="likey")

    def __str__(self):
        return self.subject

class Reply(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    replyer = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()

    def __str__(self):
        return f"{self.board} _ {self.replyer}"

trans/models.py
from django.db import models

# Create your models here.

acc/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import check_password
from .models import User
from django.contrib import messages

# Create your views here.

def index(request):
    return render(request, 'acc/index.html')

def userlogin(request):
    if request.method=="POST":
        un = request.POST.get("uname")
        up = request.POST.get("upass")
        u = authenticate(username=un, password=up)
        if u: # 로그인 성공 시
            login(request, u) # 로그인을 u에 실어야함
            messages.success(request, f"{un}님 환영합니다.")
            return redirect("acc:index")
        else:
            messages.error(request, "계정정보가 일치하지 않습니다.")
    return render(request, 'acc/login.html')


def userlogout(request):
    logout(request)
    return redirect("acc:index")

def signup(request):
    if request.method == "POST":
        un = request.POST.get("uname")
        up = request.POST.get("upass")
        uc = request.POST.get("ucomm")
        pi = request.FILES.get("upic")
        try:
            User.objects.create_user(username=un, password=up, comment=uc, pic=pi)
            return redirect("acc:login")
        except:
            un = request.POST.get("uname")
            up = request.POST.get("upass")
            uc = request.POST.get("ucomm")
            pi = request.FILES.get("upic")
            messages.error(request, "계정이름이 이미 존재합니다.")
    return render(request, 'acc/signup.html')

def profile(request):
    return render(request, "acc/profile.html")

def delete(request):
    u=request.user
    cp= request.POST.get('cpass')
    if check_password(cp, u.password):
        u.pic.delete()
        u.delete()
        return redirect("acc:index")
    else:
        messages.error(request, "비밀번호 정보가 일치하지 않습니다.")
    return redirect("acc:profile")

def update(request):
    if request.method == "POST":
        u = request.user
        ue = request.POST.get('umail')
        uc = request.POST.get('ucomm')
        up = request.FILES.get('upic')
        if up:
            u.pic.delete()
            u.pic = up
        u.email, u.comment = ue, uc
        u.save()
        return redirect("acc:profile")
    return render(request, "acc/update.html")

def chpass(request):
    u = request.user
    cp = request.POST.get('cpass')
    if check_password(cp, u.password):
        np = request.POST.get('npass')
        u.set_password(np)
        u.save()
        return redirect('acc:login')
    else:
        messages.error(request, "비밀번호가 맞지않습니다..")
    return redirect("acc:update")

board/views.py
from django.shortcuts import render, redirect
from .models import Board, Reply
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib import messages
# Create your views here.
def index(request):
    cate = request.GET.get("cate", "")
    kw = request.GET.get("kw", "")
    # ?, &
    pg = request.GET.get("page", 1)

    if kw :
        if cate == "sub":
            b = Board.objects.filter(subject__startswith=kw)
        elif cate == "wri":
            try:
                from acc.models import User
                u = User.objects.get(username=kw)
                b = Board.objects.filter(writer=u)
            except:
                b = Board.objects.none()
        elif cate == "con":
            b = Board.objects.filter(content__contains=kw)
    else:
        b = Board.objects.all()


    
    pag = Paginator(b, 5)
    obj = pag.get_page(pg)
    # pag = Paginator(레코드들, 단위)

    context = {
        "bset" : obj,
        "kw":kw,
        "cate":cate
    }
    return render(request, "board/index.html", context)

def detail(request, bpk):
    b = Board.objects.get(id=bpk)
    r = b.reply_set.all()
    context = {
        'b' : b,
        "rset" : r
    }
    return render(request, "board/detail.html", context)

def delete(request, bpk):
    b = Board.objects.get(id=bpk)
    if b.writer == request.user:
        b.delete()
    else:
        messages.error(request, "정보가 일치하지 않습니다..")
    return redirect("board:index")

def create(request):
    if request.method == "post":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        Board(subject=s, writer=request.user, content=c, pubdate=timezone.now()).save()
        return redirect("board:index")
    return render(request, 'board/create.html')

def update(request, bpk):
    b = Board.objects.get(id=bpk)
    
    if request.user != b.writer:
        messages.error(request, "정보가 일치하지 않습니다..")
        return redirect("board:index")

    if request.method == "POST":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        b.subject, b.content = s,c
        b.save()
        return redirect('board:detail', bpk)
    
    context = {
        "b" : b
    }
    return render(request, 'board/update.html', context)


def creply(request,bpk):
    b = Board.objects.get(id=bpk)
    c = request.POST.get("com")
    Reply(board=b, replyer=request.user, comment=c).save()
    return redirect("board:detail", bpk)

def dreply(request, bpk, rpk):
    r = Reply.objects.get(id=rpk)
    if request.user == r.replyer:
        r.delete()
    else:
        messages.error(request, "정보가 일치하지 않습니다..")
    return redirect("board:detail", bpk)

trans/views.py
from django.shortcuts import render
import googletrans
# Create your views here.

def index(request):
    context = {
        "ndict" : googletrans.LANGUAGES
    }
    b = request.GET.get("bf", "")
    if b:
        f = request.GET.get("fr", "")
        t = request.GET.get("to", "")
        trans = googletrans.Translator()
        a = trans.translate(b, src=f, dest=t)
        context.update({
            "btext" : b,
            "fr" : f,
            "to" : t,
            "atext" : a.text
        })
    return render(request, "trans/index.html", context)

templates/acc/index.html
{% extends 'base.html' %}

{% block con %}
    <!-- index.html -->
    {% if user.is_authenticated %}
        <h1><b>{{user}}</b> WELCOME 🎈</h1>
    {% else %}
        <h1>LOGIN FIRST! 🙏🏼</h1>
    {% endif %}

{% endblock %}

templates/acc/login.html
{% extends 'base.html' %}

{% block con %}
    <h1><b>로그인</b></h1>

    <form method="post">
        {% csrf_token %}

        <div class="mt-5">
            <input type="text" name="uname" class="form-control" placeholder="INPUT USERNAME" style="font-weight: bold;">
            <input type="password" name="upass" class="form-control mt-4" placeholder="INPUT PASSWORD" style="font-weight: bold;">
        </div>
        <div class="text-end mt-4">
            <button type="submit" class="btn btn-dark">LOGIN</button>
        </div>

    </form>
{% endblock %}

templates/acc/profile.html
{% extends 'base.html' %}

{% block con %}
    <h1><b>프로필</b></h1>
    <div class="row" >
        <div class="col-sm-5" style="margin: auto;">
            <div class="text-center mt-2">
                <img src="{{ user.getpic }}" width="100%">
            </div>
        </div>
        <div class="col-sm-7">
            <div class="mb-3 mt-3">
                <label class="form-label">USERNAME</label>
                <input type="text" disabled class="form-control" style="font-weight: bold;" value="{{ user }}">
            </div>
            <div class="mb-3">
                <label class="form-label">POINT</label>
                <input type="text" style="font-weight: bold;" disabled class="form-control" value="{{ user.point }} P">
            </div>
            <div class="mb-3">
                <label class="form-label">EMAIL</label>
                <input type="text" style="font-weight: bold;" disabled class="form-control" value="{{ user.email }}">
            </div>
            <div class="mb-3">
                <label class="form-label">COMMENT</label>
                <textarea class="form-control" disabled style="font-weight: bold; height: 100px;" >{{ user.comment }}</textarea>
            </div>
        </div>
    </div>


    <div class="text-end mt-4">
        <a href="{% url 'acc:update' %}"><button class="btn btn-dark">프로필수정</button></a>
        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
            계정삭제
        </button>
    </div>

    <!-- Modal in profile.html -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <from method="prost" action="{% url 'acc:delete' %}">
                {% csrf_token %}
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"><b>계정삭제 알림창</b></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="container">
                        <input class="form-control" type="password" placeholder="INPUT CURRENT PASSWORD">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                    <button class="btn btn-danger">삭제</button>
                </div>
            </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/acc/signup.html
{% extends 'base.html' %}

{% block con %}
    <h1><b>회원가입</b></h1>
    
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3 mt-5">
            <label class="form-label">USERNAME</label>
            <input type="text" name="uname" class="form-control">
        </div>
        <div class="mb-3">
            <label class="form-label">PASSWORD</label>
            <input type="password" name="upass" class="form-control">
        </div>
        <div class="mb-3">
            <label class="form-label">COMMENT</label>
            <textarea class="form-control" name="ucomm"></textarea>
        </div>
        <div class="mb-3">
            <label class="form-label">USERPIC</label>
            <input type="file" class="form-control" name="upic">
        </div>
        <div class="mt-4 text-end">
            <button class="btn btn-dark" style="font-weight: bold;">회원가입</button> 
        </div>
    </form>
{% endblock%}

templates/acc/update.html
{% extends 'base.html' %}

{% block con %}
    <h1><b>정보수정</b></h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token%}
    <div class="mb-3 mt-5">
        <label class="form-label">USERNAME</label>
        <input type="text" value="{{user}}" disabled class="form-control">
    </div>
    <div class="mb-3">
        <label class="form-label">EMAIL</label>
        <input type="text" name="umail" value="{{user.email}}" class="form-control">
    </div>
    <div class="mb-3">
        <label class="form-label">COMMENT</label>
        <textarea class="form-control" name="ucomm">{{user.comment}}</textarea>
    </div>
    <div class="mb-3">
        <label class="form-label">USERPIC</label>
        <input type="file" name="upic" class="form-control">
    </div>
    <div class="text-end mt-4">
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
            패스워드 변경
        </button>
        <a href="{% url 'acc:profile' %}" class="btn btn-dark">수정취소</a>
        <button class="btn btn-dark">프로필수정</button>
    </div>
    </form>


    <!-- Modal in update.html -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            
            <div class="modal-content">
                
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"><b>패스워드 변경창</b></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="POST" action="{% url 'acc:chpass' %}">
                    {% csrf_token %}
                <div class="modal-body">    
                    <div class="container mt-5 mb-5 text-center">
                        <input type="password" name="cpass" class="form-control" placeholder="INPUT CURRENT PASSWORD">
                        <input type="password" name="npass" class="form-control mt-3" placeholder="INPUT NEW PASSWORD">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                    <button class="btn btn-primary">변경</button>
                </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/base.html
<!-- base.html -->
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Django Project</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    </head>
    <body>
        
        {% if user.is_authenticated %}
        <!-- 인증된사용자 -->
            <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: rgb(0, 0, 0); font-weight: bold; font-size: 20px;">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'acc:index' %}">HOME</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'board:index' %}">BOARD</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'trans:index' %}">TRANS</a>
                            </li>
                            
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    {{ user }}
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="#">BOOKMARK</a></li>
                                    <li><a class="dropdown-item" href="{% url 'acc:profile' %}">PROFILE</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" href="{% url 'acc:logout' %}">LOGOUT</a></li>
                                </ul>
                            </li>

                        </ul>
                    </div>
                </div>
            </nav>
        
        {% else %}
            <!-- 익명의사용자 -->
            <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: rgb(1, 1, 1); font-size: 20px; font-weight: bold;">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'acc:index' %}">HOME</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'acc:login' %}">LOGIN</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'acc:signup' %}">SIGNUP</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        {% endif %}

        {% for i in messages %}
            <div class="alert {{ i.tags }} alert-dismissible fade show" role="alert">
                <strong>{{ i.tags|upper }}</strong> {{ i.message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}



        <div class="container mt-5 mb-5">
            {% block con %}
            {% endblock %}
        </div> 


        <style>
            .alert {
                font-size:larger;
                color: white;
            }
            .info {
                background-color: gray;
            }
            .success {
                background-color: blue;
            }
            .error {
                background-color: red;
            }
            .warning{
                background-color: coral;
            }

        </style>


        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    </body>
</html>

templates/board/detail.html
{% extends 'base.html' %}

{% block con %}
    
    <h1><b>{{ b.subject }}</b></h1>

    <div class="row mt-5">
        <div class="col-sm-9">
            <textarea class="form-control" style="height: 200px;" disabled>{{ b.content }}</textarea>
        </div>
        <div class="col-sm-3">
            <img src="{{ b.writer.getpic }}" width="100%">
            <div class="text-center mt-4">
                <h5>written by <b>{{ b.writer }}</h5></b>
            </div>
            <div class="text-end mt-3">
                <h6>{{ b.pubdate|date:'Y년 n월 j일 H:i' }}</h6>
            </div>
        </div>
    </div>

        <div class="text-end-mt4 mb-3">
            <a class="btn btn-dark" href="{% url 'board:index' %}">글 목록</a>

            {% if user == b.writer %}
                <a class="btn btn-secondary" href="{% url 'board:update' b.id %}">글 수정</a>
                <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    글삭제
                </button>
            {% endif %}
        </div>
    
    
    
    <hr>

    <form method="POST" action="{% url 'board:creply' b.id %}">
        {% csrf_token %}
        <div class="row mt-4 mb-5">
            <div class="col-sm-10">
                <input type="text" name="com" class="form-control">
            </div>
            <div class="col-sm-2">
                <button class="btn btn-primary" style="width: 100%;">댓글등록</button>
            </div>
        </div>
    </form>

    {% for i in rset %}
    <div class="row mt-5">
        <div class="col-sm-3 text-center">
            <img src="{{ i.replyer.getpic }}" width="70%" class="rounded-circle">
            <div class="mt-2">
                <h5><b>{{ i.replyer }}</b></h5>                
            </div>
        </div>
        <div class="col-sm-9" style="margin: auto;">
            <textarea class="form-control" disabled style="height: 100px;">{{ i.comment }}</textarea>
            {% if i.replyer == user %}
            <div class="text-end">
                <a class="btn btn-danger btn-sm mt-5" href="{% url 'board:dreply' b.id i.id %}">댓글삭제</a>
            </div>
            {% endif %}
        </div>
        
    </div>

    {% empty %}
        <div class="text-center mt-5 mb-5">
            <h4>첫번째 댓글을 달아주세요!</h4>
        </div>
    
    {% endfor %}

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"><b>게시글 삭제 알림창</b></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <b>{{ b.subject }}</b>를 정말로 삭제 하시겠습니까?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                <a class="btn btn-danger" href="{% url 'board:delete' b.id %}">삭제</a>
            </div>
        </div>
        </div>
    </div>

{% endblock %}

templates/board/index.html
{% extends 'base.html' %}
{% block con %}

    {% load mathfilters %}

    <h1><b>JWS 게시판</b></h1>

    <div class="text-end">
        <a class="btn btn-dark" href="{% url 'board:create' %}">게시글생성</a>
    </div>

    <table class="table mt-4 table-hover">
        <thead>
            <tr class="table-dark">
                <th scope="col">NO</th>
                <th scope="col">SUBJECT</th>
                <th scope="col">SUMMARY</th>
                <th scope="col">WRITER</th>
                <th scope="col">LIKEY</th>
            </tr>
        </thead>
        <tbody>
            {% for i in bset %}
                <tr>
                    <th scope="row">{{ bset.start_index|add:forloop.counter0 }}</th>
                    <td><a href="{% url 'board:detail' i.id %}" class="sub">{{ i.subject }}</a></td>
                    <td>{{ i.content|truncatewords:10 }}</td>
                    <td>{{ i.writer }}</td>
                    <td>0</td>
                </tr>
            {% empty %}
                <tr>
                    <th colspan="5">
                        {% if kw %}
                            검색결과가 없습니다..❌
                        {% else %}
                            첫번째 게시글을 작성해주세요 🙏🏻
                        {% endif %}
                    </th>
                </tr>
            {% endfor %}
          
        </tbody>
    </table>
<!--
    {% if bset.has_previous %}
        <a href="{% url 'board:index' %}?page=1"><button>처음</button></a>
        <a href="{% url 'board:index' %}?page={{ bset.previous_page_number }}"><button>이전</button></a>        
    {% else %}
        <button disabled >처음</button>
        <button disabled >이전</button>
    {% endif %}

    {% for i in bset.paginator.page_range %}
        {% if bset.number|add:4 >= i and i >= bset.number|sub:4 %}
            <a href="{% url 'board:index' %}?page={{i}}"><button {% if bset.number == i %} disabled {% endif%}>{{i}}</button></a>
        {% endif %}
    {% endfor %}

    {% if bset.has_next %}
        <a href="{% url 'board:index' %}?page={{ bset.next_page_number }}"><button>다음</button></a>
        <a href="{% url 'board:index' %}?page={{ bset.paginator.num_pages }}"><button>마지막</button></a>
    {% else %}
        <button disabled>마지막</button>
        <button disabled>다음</button>
    {% endif %}
-->


    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
        
            {% if bset.has_previous %}
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page=1&cate={{cate}}&kw={{kw}}">처음</a></li>
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{ bset.previous_page_number}}&cate={{cate}}&kw={{kw}}">이전</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link">처음</a></li>
                <li class="page-item disabled"><a class="page-link">이전</a></li>
            {% endif %}


            {% for i in bset.paginator.page_range %}
                 {% if bset.number|add:4 >= i and i >= bset.number|sub:4 %}
        
            <li class="page-item {% if bset.number == i %} active {% endif %}"><a class="page-link" href="{% url 'board:index' %}?page={{i}}&cate={{cate}}&kw={{kw}}">{{i}}</a></li>
                {% endif %}
            {% endfor %}

            {% if bset.has_next %}
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{ bset.next_page_number }}&cate={{cate}}&kw={{kw}}">다음</a></li>
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{ bset.paginator.num_pages}}&cate={{cate}}&kw={{kw}}">마지막</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link">다음</a></li>
                <li class="page-item disabled"><a class="page-link">마지막</a></li>
            {% endif %}
            </li>
        </ul>
    </nav>




    <form>

        <div class="row mt-4">

            <div class="col-sm-2">
                <select name="cate" class="form-select">
                    <option value="sub" {% if cate == "sub" %} selected {% endif %}>제목</option>
                    <option value="wri" {% if cate == "wri" %} selected {% endif %}>작성자</option>
                    <option value="con" {% if cate == "con" %} selected {% endif %}>내용</option>
                </select>
            </div>

            <div class="col-sm-8">
                <input type="text" class="form-control" name="kw" value="{{kw}}">
            </div>

            <div class="col-sm-1">
                <button class="btn btn-dark" style="width: 100%">검색</button>
            </div>

            <div class="col-sm-1">
                <a href="{% url 'board:index' %}" class="btn btn-dark" style="width: 100%">초기화</a>
            </div>

        </div>
    </form>





    <style>
        .sub{
            text-decoration: none;
            color: black;
            font-weight: bold;
        }
        .sub:hover{
            color:rgb(16, 8, 233);
        }
    </style>
{% endblock %}

templates/trans/index.html
{% extends 'base.html' %}

{% block con %}
    <h1><b>번역해ZOOM</b></h1>

    <form name="transForm">
        <div class="row mt-5">
            <div class="col-sm-5">
                <textarea class="form-control" name="bf" style="height: 200px;">{{ btext }}</textarea>
            </div>
            <div class="col-sm-2" style="margin: auto;">
                <select clas="form-selcet" name="fr">
                    {% for code, name in ndict.items %}
                        <option value="{{code}}" {% if fr %}{% if fr == code %} selected {% endif %}{% else %}{% if fr == 'en' %} selected {% endif %}{% endif %}>{{name|upper}}</option>
                    {% endfor %}
                </select>
                <button type="button" onclick="check()" class="btn btn-dark mt-3 mb-3" style="width: 100%">번역</button>
                <a href="{% url 'trans:index' %}?bf={{atext}}&to={{fr}}&fr={{to}}"><button type=button class="btn btn-dark mt-3 mb-3" style="width: 100%" {% if not atext %}disabled{% endif %}>체인지</button></a>
                <select clas="form-selcet" name="to">
                    {% for code, name in ndict.items %}
                        <option value="{{code}}" {% if to %}{% if to == code %} selected {% endif %}{% else %}{% if code == 'ko'%} selected {% endif %}{% endif %}>{{name|upper}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-sm-5">
                <textarea class="form-control" style="height: 200px;" disabled>{{ atext }}</textarea>
            </div>
        </div>
    </form>

    <script>
        function check(){
            tf = document.transForm;
            if(!tf.bf.value){
                alert("번역할 문장을 입력해주세요...")
            }else if (tf.fr.value == tf.to.value){
                alert("서로 다른 나라를 선택해주세요...")
            }else{
                tf.submit();
            }
        }

    </script>
{% endblock %}